name: "Hugo Build, S3 Deploy, Cloudfront Invalidate"
on:
  workflow_call:
    inputs:
      IAM_DEPLOYMENT_ROLE_ARN:
        description: 'The IAM role ARN to assume'
        required: true
        type: string
      AWS_REGION:
        description: 'The AWS region to deploy to'
        required: true
        type: string
      S3_BUCKET_NAME:
        description: 'The S3 bucket name to deploy to'
        required: true
        type: string
      CLOUDFRONT_DISTRIBUTION_ID:
        description: 'The Cloudfront distribution ID to invalidate'
        required: true
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        description: 'The Docker Hub username'
        required: true
      DOCKERHUB_PASSWORD:
        description: 'The Docker Hub password'
        required: true
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read

jobs:
  run-docker-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Configure aws credentials
      id: credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{inputs.IAM_DEPLOYMENT_ROLE_ARN}}
        aws-region: ${{inputs.AWS_REGION}}
        output-credentials: true

    - name: Pull Docker Image
      run: docker pull crewdereksl/s3-cloudfront-hugo-deployment:latest

    - name: Deploy HUGO website to S3 and Cloudfront
      run: |
        docker run \
        -e AWS_ACCESS_KEY_ID=${{ steps.credentials.outputs.aws-access-key-id }} \
        -e AWS_SECRET_ACCESS_KEY=${{ steps.credentials.outputs.aws-secret-access-key }} \
        -e AWS_SESSION_TOKEN=${{ steps.credentials.outputs.aws-session-token }} \
        -e AWS_REGION=${{ inputs.AWS_REGION }} \
        -e S3_BUCKET_NAME=${{ inputs.S3_BUCKET_NAME }} \
        -e CLOUDFRONT_ID=${{ inputs.CLOUDFRONT_DISTRIBUTION_ID }} \
        -v ./Hugo:/app/hugo \
        crewdereksl/s3-cloudfront-hugo-deployment:latest
      shell: bash